Remove Ubuntu 20.04 job from GitHub Actions
Move the tested compiler versions there to old-compilers.yml.

Add a sanitizer workaround for Ubuntu 22.04-packaged clang 11.

Fix a typo that prevented enabling -fsanitize=implicit-bitfield-conversion for
clang 19 or later.

Add extra CMake diagnostics in the case of its failure to build.yml and
old-compilers.yml scripts.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -403,6 +403,7 @@ jobs:
             export CC=clang
             export CXX=clang++
           fi
+          set +e
           cmake -B build "$GITHUB_WORKSPACE" "$CBT" -DSTANDALONE=ON \
               -DMAINTAINER_MODE=ON -DIWYU=ON \
               "-DSANITIZE_ADDRESS=${SANITIZE_ADDRESS}" \
@@ -410,6 +411,20 @@ jobs:
               "-DSANITIZE_UB=${SANITIZE_UB}" \
               "-DSTATIC_ANALYSIS=${STATIC_ANALYSIS}" "-DCOVERAGE=${COVERAGE}" \
               "-DAVX2=${AVX2}" "${EXTRA_CMAKE_ARGS[@]}"
+          CMAKE_EXIT_CODE=$?
+          if [ $CMAKE_EXIT_CODE -ne 0 ]; then
+            if [ -f build/CMakeFiles/CMakeError.log ]; then
+              echo "::group::CMakeError.log"
+              cat build/CMakeFiles/CMakeError.log
+              echo "::endgroup::"
+            fi
+            if [ -f build/CMakeFiles/CMakeOutput.log ]; then
+              echo "::group::CMakeOutput.log"
+              cat build/CMakeFiles/CMakeOutput.log
+              echo "::endgroup::"
+            fi
+            exit 1
+          fi
 
       - name: Build
         working-directory: ${{github.workspace}}/build
